### ISSUE TITLE
Stock management issue: Failed payments sets order status to "payment pending" and reduces stock

### ISSUE THREAD

**Issue by meilione** [pfpayments/woocommerce#10]
Hi 

We have stock management enabled and all our products are unique, hence we have only one item per product available. 

When a payment (Twint, Postfinance,.) is aborted or fails, woocommerce is reducing the stock by 1, sets the order status to "payment pending" and returns the customer back to the checkout. However on the checkout the product is not available anymore and the customer can't try another payment method.

Thanks for looking into that. I am happy to provide more details if required.

**Comment by theodorspringwallee** [comment]
Dear [meilione](https://github.com/meilione)

Thank you for your request.

We aren't able to reproduce your issue in our test systems. We tried with the following two options:

![image](https://user-images.githubusercontent.com/85299706/203503281-c82fc911-cf0b-4a38-86f8-d7f9e3939ea8.png)

![image](https://user-images.githubusercontent.com/85299706/203503164-69cf5678-cbf8-4f0f-acd9-90d4c7901f39.png)

Please let us know if you chose another option for this.

If you used the same options, we appreciate if you could contact the PostFinance support, that they can check your issue: https://www.postfinance.ch/de/support/hotline.html

Thank you for your answers.

Best regards

**Comment by meilione** [comment]
The settings are the same you have posted. However I have noticed, that issue was with the setting in woocommerce "Ware reservieren (Minuten)". There I had 60 minutes set, which caused the problem. Now the Items are not reserved (which is ok in our case). and it works.

<img width="509" alt="Bildschirmfoto 2022-11-23 um 13 49 30" src="https://user-images.githubusercontent.com/1598799/203552377-982b178d-acce-4948-a223-49fd9fc8717e.png">

**Comment by theodorspringwallee** [comment]
Dear [meilione](https://github.com/meilione)

Thank you for your feedback. 

Best regards
