### ISSUE TITLE
When will Woocommerce 7.5.+ support come?

### ISSUE THREAD

**Issue by ahmetanilsen** [pfpayments/woocommerce#16]
The current plugin does not work with woocommerce 7.5.+.

**Comment by masteradhoc** [comment]
@ahmetanilsen @theodorspringwallee i think this is available now since https://github.com/pfpayments/woocommerce/releases/tag/2.1.12 right? Although it seems WC 7.6 (https://github.com/woocommerce/woocommerce/releases/tag/7.6.0) is not yet supported

**Comment by theodorspringwallee** [comment]
Dear [masteradhoc](https://github.com/masteradhoc), [ahmetanilsen](https://github.com/ahmetanilsen)

Now also WC 7.6 will be supported: https://github.com/pfpayments/woocommerce/releases

If you still have issues, please let us know.

Best regards
