### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'submit')

### ISSUE THREAD

**Issue by kbverlag** [pfpayments/woocommerce#17]
Hallo zusammen

Seit dem neusten Update haben wir das Problem, dass auf der Checkout-Seite, nach dem Absenden, nach einigen Sekunden folgende Fehlermeldung in der Konsole kommt:

jquery-migrate.min.js?ver=3.4.0:2 JQMIGRATE: Migrate is installed, version 3.3.2
PT4sT.js?ver=HmV:2 execute
PT4sT.js?ver=HmV:2 unlocked
checkout.js?ver=1:452 Uncaught TypeError: Cannot read properties of undefined (reading 'submit')
    at Object.process_order_created (checkout.js?ver=1:452:71)
    at options.success (checkout.js?ver=1:204:19)
    at c (jquery.min.js?ver=3.6.3:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js?ver=3.6.3:2:29072)
    at l (jquery.min.js?ver=3.6.3:2:80045)
    at XMLHttpRequest.<anonymous> (jquery.min.js?ver=3.6.3:2:82499)
process_order_created @ checkout.js?ver=1:452
options.success @ checkout.js?ver=1:204
c @ jquery.min.js?ver=3.6.3:2
fireWith @ jquery.min.js?ver=3.6.3:2
l @ jquery.min.js?ver=3.6.3:2
(anonym) @ jquery.min.js?ver=3.6.3:2
load (async)
send @ jquery.min.js?ver=3.6.3:2
ajax @ jquery.min.js?ver=3.6.3:2
s.ajax.s.ajax @ jquery-migrate.min.js?ver=3.4.0:2
submit @ checkout.min.js?ver=7.5.1:1
dispatch @ jquery.min.js?ver=3.6.3:2
y.handle @ jquery.min.js?ver=3.6.3:2

Die  Bestellung geht dann nicht weiter. Habt ihr eine Idee, woran das liegen könnte?

PHP: 7.4.33
Wordpress: 6.2
WooCommerce 7.5.1

**Comment by theodorspringwallee** [comment]
Hallo [kbverlag](https://github.com/kbverlag)

Vielen Dank für Ihr Feedback. Wir werden dies überprüfen und uns dann wieder melden.

Freundliche Grüsse

**Comment by theodorspringwallee** [comment]
Hallo [kbverlag](https://github.com/kbverlag)

Wir konnten den Fall bei uns in unseren neusten Plugin Version prüfen.

**Bei uns geht die Bestellung durch** (allerdings mit einer anderen jQuery Version "JQMIGRATE: Migrate is installed, version 3.4.0", die Fehlermeldung von Ihnen haben wir jedoch nicht erhalten.)

PFC Version: 2.1.12
WordPress: 6.2
WooCommerce 7.6.0
PHP: 7.4

Können Sie es bitte in der neusten Pluginversion (2.1.12) nochmals versuchen? (diese supportet auch offiziell WooCommerce 7.5)

Sollte es dann immer noch nicht gehen, bitte kontaktieren Sie den PostFinance Support:  https://www.postfinance.ch/de/support/hotline.html

Freundliche Grüsse

**Comment by kbverlag** [comment]
Besten Dank, mit der neusten Version funktioniert es wieder.
