### ISSUE TITLE
Title of the credit cards method

### ISSUE THREAD

**Issue by amarineau** [pfpayments/woocommerce#2]
Hello ! 

I have seen the title Mastercard and I wonder if it should not be replaced by "Credit Card" since we can choose the brand of the card afterwards.

What do you think about that? 

Thanks ! 

Best regards 

Alan

**Comment by theodorspringwallee** [comment]
Hello [amarineau](https://github.com/amarineau)

If this is still a question for you, please contact the PostFinance Support: https://www.postfinance.ch/en/support/hotline.html
