### ISSUE TITLE
Zahlung / Per Nachnahme – Barzahlung bei Abholung

### ISSUE THREAD

**Issue by KuhnDaniel** [pfpayments/woocommerce#21]
I have the following error when checking out Payment:
We use cash on delivery on collection, which also worked. Now I get an error: 

Uncaught InvalidArgumentException: Missing the required parameter $id when calling read in /home/clients/xy/sites/xy.ch/wp-content/plugins/woo-postfinance-checkout/postfinancecheckout-sdk/lib/ Service/TransactionService.php:1691 Stack trace: #0
![Error Zahlung bei Abholung-Screenshot 2023-05-22 002753](https://github.com/pfpayments/woocommerce/assets/36757260/8bfe4491-6d52-49c5-9d19-61c73d2ba419)

**Comment by masteradhoc** [comment]
Same here..

Fatal error: Uncaught InvalidArgumentException: Missing the required parameter $id when calling read in /home/httpd/vhosts/xxxxxxxxxxx/httpdocs/wp-content/plugins/woo-postfinance-checkout/postfinancecheckout-sdk/lib/Service/TransactionService.php:1691

**Comment by theodorspringwallee** [comment]
Dear [KuhnDaniel](https://github.com/KuhnDaniel), [masteradhoc](https://github.com/masteradhoc)

Thanks for your inputs.

I also can reproduce this and forwarded this BUG to our developers.

Best regards
