### ISSUE TITLE
Checkout Page Error Redirect

### ISSUE THREAD

**Issue by kbverlag** [pfpayments/woocommerce#22]
Seit dem neusten Update haben wir auf der Checkout Seite einen "kritischen Fehler". Der Fehler wird hier von dem Plugin der "PostFinance" verursacht. Dadurch, dass eine andere Zahlungsart verwendet wird, fehlt die ID von PostFinance und wirft eine Exception.

Wenn ich mir die Hooks des Plugins ansehe, dann kommt es daher, weil das Plugin auf der finalen Checkout-Seite versucht den User inkl. der ID von PostFinance weiterzuleiten obwohl es diese ID nicht gibt. Der Hook greift wohl ohne Einschränkung bei jeder Zahlungsart:

add_action( 'woocommerce_thankyou' , array( $this, 'secure_redirect_order_confirmed', ): 

Es sollte im Plugin überprüft werden, ob die die entsprechende ID überhaupt vorhanden ist:

`if($wc_transaction_info->get_transaction-id())

**Comment by E1NSER** [comment]
We can confirm that this bug is fixed in the current version
