### ISSUE TITLE
Error : The line item discount must have the same sign as the line item amount.

### ISSUE THREAD

**Issue by saiif** [pfpayments/woocommerce#24]
when there is a coupon code 
https://github.com/pfpayments/woocommerce/blob/4e5e65496b37c488085f8ec4cede316fb7fa0c7b/includes/packages/coupon/class-wc-postfinancecheckout-packages-coupon-discount.php#LL166C3-L166C3
resolution : 
`
		return -1 * abs($coupon_percentage_discount);
`

**Comment by theodorspringwallee** [comment]
Dear [saiif](https://github.com/saiif)

Thanks for your input.

Please, can you explain your change request?

I see the concerned method is called over the WP filter here: 
![grafik](https://github.com/pfpayments/woocommerce/assets/85299706/c6c904e4-d028-4f33-b280-db9dc757672c)

![grafik](https://github.com/pfpayments/woocommerce/assets/85299706/6553731d-79b9-48fe-ac44-7d5335948bbc)
https://github.com/pfpayments/woocommerce/blob/4e5e65496b37c488085f8ec4cede316fb7fa0c7b/includes/service/class-wc-postfinancecheckout-service-line-item.php#L110

So the if-statement is only called, when the coupon discount is applied, respectively the concerned WP filter has returned a positive amount.

With your proposal (`-1 * abs($coupon_percentage_discount)`), it would be in any case a negative amount, returned by the WP filter. 

Thanks for your answer.

Best regards

**Comment by saiif** [comment]
hi @theodorspringwallee 
i have this response from Api, 
`2023-06-21T13:10:18+00:00 ERROR WC_PostFinanceCheckout_Service_Transaction : load_and_update_transaction_from_session : 946 : Error 442 connecting to the API (https://checkout.postfinance.ch/api/transaction/update?spaceId=xxxx) : {"date":"2023-06-21T13:10:18.224Z","defaultMessage":"The line item discount must have the same sign as the line item amount.","id":"rVEyWJnCiVXs-r08F4LaecYcgPVUAhXF1-S9y182A (2023-06-21T13:10:18.224Z)","message":"The line item discount must have the same sign as the line item amount.","type":"DEVELOPER_ERROR"}
`
it worked with negative value

**Comment by theodorspringwallee** [comment]
Dear [saiif](https://github.com/saiif)

Many thanks for your answer.

I checked this error response with one of our plugin developers. We currently have a BUG ticket open on our side, that will fix this issue.

But the final solution seems to be more complex, and might take a longer time till this is fixed.

Nevertheless, many thanks for your input. 

Hopefully we soon can provide an official fix for this.

Best regards

**Comment by SGiumelli** [comment]
Any update on this issue ? Still a thing with the lastest version.

**Comment by theodorspringwallee** [comment]
Dear [SGiumelli](https://github.com/SGiumelli)

Did you toggle already the line item consistency option in the plugin settings?
![grafik](https://github.com/pfpayments/woocommerce/assets/85299706/7141190f-de1e-4228-82f3-1a18a25a841c)

If this does not work for you we need to check your issue individually, please contact for this the PF Support:
https://www.postfinance.ch/de/support/hotline.html

Best regards
