### ISSUE TITLE
Wo sehe ich welche WooCoomerce Version ich verwenden sollte?

### ISSUE THREAD

**Issue by Diventusgmbh** [pfpayments/woocommerce#29]
Ich habe vorhin mit dem Support telefoniert, ich sollte hier auf diesem Github sehen, welche WooCoomerce Version usw. wir verwenden sollten. Mit der neuesten hat Checkout ja aktuell Probleme unsere Zahlungen gehen nicht ein...

**Comment by theodorspringwallee** [comment]
Lieber [Diventusgmbh](https://github.com/Diventusgmbh)

Aktuell sind wir mit WooCommerce 8 in Kombination mit dem Blocks Checkout inkompatibel. Daran arbeiten wir.

Sollte dies ihre Fragen nicht beantworten, bitte lassen Sie sich beim PF Support ein Ticket erstellen, damit ihr Fall untersucht werden kann: https://www.postfinance.ch/de/support/hotline.html

Freundliche Grüsse

**Comment by Diventusgmbh** [comment]
Hallo Theodor

Meine Frage ist, wo ich im Github sehe, mit welcher WooCoomerce Version PF Checkout Kompatibel ist, gem. PostFinance Mitarbeiter sehe ich es hier, das Ziel wäre, dass ich nicht ein Problem eröffnen muss, sondern ich nur kurz hier rein schauen kann und direkt sehe "Aha Version..." ist kompatibel.

**Comment by theodorspringwallee** [comment]
Hallo [Diventusgmbh](https://github.com/Diventusgmbh)

Womit unsere Plug-ins getestet wurden, sehen Sie immer in den Releases: https://github.com/pfpayments/woocommerce/releases

Beste Grüsse
