### ISSUE TITLE
Order numbers in stead of order id's

### ISSUE THREAD

**Issue by joldnl** [pfpayments/woocommerce#3]
The plugin reports orders to PostFinance with the `get_id()` of a WooCommerce order, in stead of the actual `get_order_number`.
If you have, for example a custom order number set up, or use a custom order number plugin like we do, this causes a lot of trouble with our accounting software, and is very easily fixed with a wordpress filter.

Current code in includes/service/class-wc-postfinancecheckout-service-transaction.php on line 527: 
```$transaction->setMerchantReference($order->get_id());```

Should be:
```$transaction->setMerchantReference($order->get_order_number());```

Funny that on the next line (528) the `setInvoiceMerchantReference` method does use the order number.

**Comment by vttn** [comment]
Hello @joldnl we have your ticket in our backlog. We will get to it as soon as possible. You will receive updates via the support ticket you created.
