### ISSUE TITLE
new Woocommerce Blocks Checkout Template (bundled with Woocommerce 8.0.0+)

### ISSUE THREAD

**Issue by KuhnDaniel** [pfpayments/woocommerce#33]
Hallo Team
Die Fehlermeldung irritiert doch sehr!
Mit WC 8.1.1 funktioniert der Checkout bei uns!
Warum kommt immer noch die Fehlermeldung.

Schon der Max Check war nervig und es gibt immer wieder unnötige Anfragen!
Habe den Wert jetzt auf 8.1.1 angepasst. Wenigstens eine Meldung weniger.

Beste digitale Grüsse
Daniel

**Comment by theodorspringwallee** [comment]
Hallo [KuhnDaniel](https://github.com/KuhnDaniel)

Es freut uns zu hören, dass WC 8.1.1 bei Ihnen mit unserem Plugin funktioniert.

Sobald unsere Entwickler offiziell WC 8.1.1 mit dem PFC Plugin getestet haben, werden wir es auch offiziell so anpassen können.

Beste Grüsse
