### ISSUE TITLE
Message Woocommerce Blocks Checkout Template

### ISSUE THREAD

**Issue by kbverlag** [pfpayments/woocommerce#34]
Why can't I hide this message? We do not use blocks.

> The PostFinanceCheckout plugin is currently incompatible with the new Woocommerce Blocks Checkout Template (bundled with Woocommerce 8.0.0+). We are working on compatibility. If payment methods do not appear for you when using PostFinanceCheckout with checkout blocks, please replace the checkout page block with the shortcode for the checkout:
> 
> [woocommerce_checkout]

**Comment by theodorspringwallee** [comment]
Dear [kbverlag](https://github.com/kbverlag)

Our developers will check this.

Best regards

**Comment by SGiumelli** [comment]
Is this plugin still supported ? I mean there are issues open for month without answer or fixes.

**Comment by theodorspringwallee** [comment]
Dear [kbverlag](https://github.com/kbverlag), [SGiumelli](https://github.com/SGiumelli)

Sorry, this git issue was going under.

Here is the answer from our developers:
> This message is based on the woocommerce version, not if blocks are enabled or not. However, this isn’t really a bug and the message will be removed when we implement support for blocks

Best regards

**Comment by kbverlag** [comment]
Nevertheless, you could offer the "Hide" button
