### ISSUE TITLE
DEVELOPER_ERROR

### ISSUE THREAD

**Issue by Studio24-Matteo** [pfpayments/woocommerce#35]
Hi, I have this error on checkout page:
"DEVELOPER_ERROR: The title must have between 2 and 40 characters."

Checkout is blocked and Woocommerce don't find any payment method.

thank you

**Comment by theodorspringwallee** [comment]
Dear [Studio24-Matteo](https://github.com/Studio24-Matteo)

We can't reproduce your issue in our test systems.

Therefore, please contact the PF Support directly: https://www.postfinance.ch/de/support/hotline.html

Best regards
