### ISSUE TITLE
payment methods disappear

### ISSUE THREAD

**Issue by mzwygart** [pfpayments/woocommerce#7]
When I load order confirmation page, payment methods show and then disappear.

I have this error in js console:
```
Uncaught ReferenceError: wc_postfinancecheckout_checkout is not defined
```

**Comment by theodorspringwallee** [comment]
Dear [mzwygart](https://github.com/mzwygart)

On our side we can see and pay with the payment methods on the checkout page in our test systems.

Therefore, please can you contact the PostFinanceCheckout support, that they can check your issue: https://www.postfinance.ch/en/private/support/hotline.html
