### ISSUE TITLE
Coupons and pfcheckout

### ISSUE THREAD

**Issue by tobinski** [pfpayments/woocommerce#9]
Hi postfinance

How to use this payment gateway with coupons? If I apply a coupon the transaction with the gateway fails. I can disable "Enforce Consistency" and it works, but then the final amount is not correct. f.e. a customer buys a product for 80.- and apply a coupon for 50.-. If I deactivate enforce consistency it will charge the customer 80.-.

**Comment by theodorspringwallee** [comment]
Dear [tobinski](https://github.com/tobinski)

Without the "enforce consistency" on our test-system to coupons are working properly:

![woo_tx](https://user-images.githubusercontent.com/85299706/201719196-cf3c0728-6029-4426-9aca-9a6bf39721cb.png)

![wallee_tx](https://user-images.githubusercontent.com/85299706/201719217-72783075-4a3a-4bab-afa7-bd9fab4bd64e.png)

Are you using the coupons of wordpress?
![image](https://user-images.githubusercontent.com/85299706/201719926-a1d36e81-ac8c-4692-bc52-49a497c077d4.png)

Thank you for your answer.

Best regards

**Comment by tobinski** [comment]
I use [WooCommerce Smart Coupons](https://woocommerce.com/products/smart-coupons/) for my coupons and gift cards. If I deactivate the plugin, pf-checkout seems to work. Unfortunately there are 1000+ gift cards out there. So to just switch the plugin is not an option.  Any workaround to fix this problem?

**Comment by theodorspringwallee** [comment]
Dear [tobinski](https://github.com/tobinski) 

I saw we have a feature-request for this in our ticket system, to work for the Smart Coupons compatibility.
But till now we don't have a starting date for this.

In the meanwhile we recommend you to use the integrated coupon system of WooCommerce.

Best regards

**Comment by SGiumelli** [comment]
> I cant use the integrated system. We have 1000+ giftcard out there, which will not longer work if I switch to postfinance checkout. I will try to make build a workaround, otherwise I can't migrate to the new pf-checkout.
> 
> Is there an open roadmap?
> 
> Best regards

Hey did you ever got an answer from postfinance ?

**Comment by theodorspringwallee** [comment]
Dear [SGiumelli](https://github.com/SGiumelli)

The Smart Coupon plugin is compatible with the PFC plugin.

You also can see, that we have added this to our releases: https://github.com/pfpayments/woocommerce/releases?q=smart+coupon&expanded=true

If you still have issues with coupons, please contact the PF support directly: https://www.postfinance.ch/de/support/hotline.html

Best regards
